# Generated by Django 4.0.3 on 2022-04-03 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Text')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('ranking', models.IntegerField(default=0, verbose_name='Ranking')),
                ('status', models.TextField(choices=[('new', 'New'), ('moderated', 'Moderated')], default=('new', 'New'), verbose_name='Status')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='DateTime')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quote',
                'verbose_name_plural': 'Quotes',
                'db_table': 'quote',
            },
        ),
    ]
