# Generated by Django 4.0.3 on 2022-04-03 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='user',
        ),
    ]
